config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  get '/items', to: 'items#index'
  #  get '/items/create', to: 'items#create'

  resources :items do
    get :upvote,    on: :member
    get :expensive, on: :collection
    get :last, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many   :positions
    belongs_to :user
    has_many   :items, through: :positions

end 

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord

  mount_uploader :image, ImageUploader

  validates :price, { numericality: {greater_than: 0, allow_nil: true}}
  validates :name, :description, presence: true

  has_many :positions
  has_many :carts, through: :positions

  has_many :comments, as: :commentable


=begin
  after_initialize { puts "initialize" }
  after_save {}
  after_create {}
  after_update {}
  after_destroy {}
=end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

end

app/models/position.rb
class Position < ApplicationRecord

  belongs_to :item
  belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord
  #mount :avatar, AvatarUploader
  has_one  :cart
  has_many :orders
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :set_locale

  def rant_params
    params.require(:item).permit(:name, :description, :weight, :price, :real, :image, :image_cache)
  end

  private

    def render_403
      render file: "public/403.html", status: 403
    end

    def render_404
      render file: "public/404.html", status: 404
    end

    def check_if_admin
      render_403 unless params[:admin]
    end

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    before_action :find_item, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :check_if_admin, only: [:edit, :update, :new, :create]


    def index
      @items = Item.all
      flash[:notice] = "hello"
    end

    def expensive
      @items = Item.where("price > 1000")
      render "index"
    end

    def last
      @item = Item.last
      puts @item.inspect

      #render json: { item_name:  @item.name}
      render "last"
    end

    def show
      unless @item
        render text: "Page not found", status: 404
      end
    end

    def new
      @item = Item.new
    end

    def edit

    end

    def create
        @item = Item.create(rant_params)
        if @item.errors.empty?
          redirect_to item_path(@item)
        else
          render "new"
        end
    end

    def update
      @item.update_attributes(rant_params)
      if @item.errors.empty?
        redirect_to item_path(@item)
      else
        render "edit"
      end

    end

    def destroy
      @item.destroy
      redirect_to action: "index"
      ItemsMailer.item_destroyed(@item).deliver
    end

    def upvote
      @item.increment!(:votes_count)
      redirect_to action: :index
    end

    private
      def find_item
        @item = Item.where(id: params[:id]).first
        render_404 unless @item
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        UserMailer.welcome_email(@user)

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def urls_to_images(s)
    #s.gsub! /\s(http:\/\/.*?\.(png|jpg|jpeg))\s/, '<img src="\1"/>'
    s.gsub! /\s(http:\/\/.*?)\s/, '<img src="\0"/>'
    s.html_safe
  end

=begin
  def urls_to_links(s)
    s.gsub! /\s(http:\/\/.*?)\s/,
            '<a href="\1">\1</a>'
  end
=end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.haml
%h1 Edit new item
= form_for @item, :html => {:multipart => true}  do |f|
  %table
    %thead
      %th цена:
      %th имя:
      %th описание:
      %th вес:
      %th Image
    %tbody
      %td= f.text_field :price
      %td= f.text_field :name
      %td= f.text_field :description
      %td= f.text_field :weight
      %td
        = image_tag(@item.image.url) if @item.image?
        = f.file_field :image
        = f.hidden_field :image_cache
      = hidden_field_tag :admin, 1
  %div= f.submit "save item"
#test test jQuery

app/views/items/index.html.haml
%h1 all items
%table
  %thead
    %th ID
    %th цена:
    %th имя:
    %th описание:
    %th вес:
    %th Рейтинг
    %th
  - @items.each do |f|
    %tbody
      %td= f.id
      %td= f.price
      %td= link_to f.name, item_path(f)
      %td= f.description
      %td= f.weight
      %td
        = f.votes_count
        , #{link_to "+", upvote_item_path(f)}
      %td= link_to "удалить", f, method: :delete, data: { confirm: "точно удалить?"}
%p= t :hello
%p= flash[:notice]

app/views/items/last.js.haml
$('#test').before("<p>#{@item.name}</p>");

app/views/items/new.html.haml
%h1 Create new item
= simple_form_for @item, :html => {:multipart => true} do |f|
  %table
    %thead
      %th цена:
      %th имя:
      %th описание:
      %th вес:
      %th Image:
    %tbody
      %td= f.text_field :price, label: 'No special characters.'
      %td= f.text_field :name, label: 'Your name please', error: 'name is mandatory, please specify one'
      %td= f.text_field :description, placeholder: 'Описание'
      %td= f.text_field :weight
      %td
        = image_tag(@item.image) if @item.image?
        = f.file_field :image
        = f.hidden_field :image_cache
      =hidden_field_tag :admin, 1
  = f.submit "Make item"

#test.btn.btn-success add item
#selectLastItem.btn.btn-danger Select Last Item

app/views/items/show.html.haml
%h1= @item.name
%ul
  %li
    Цена: #{@item.price} руб.
  %li
    Вес: #{@item.weight} кг.
  %li
    Описание: #{urls_to_images(@item.description)}
  %li= image_tag(@item.image)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyStore
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :login
    = f.text_field :login
  .actions
    = f.submit

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Name
      %th Email
      %th Login
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.login
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
%p
  %strong Email:
  = @user.email
%p
  %strong Login:
  = @user.login
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path